name: onboarding_screen
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  google_fonts: ^4.0.4
  shared_preferences: ^2.0.7
  form_field_validator: ^1.1.0
  flutter_svg: ^2.0.5
  get:
  firebase_auth: ^4.5.0
  firebase_core: ^2.12.0
  easy_sidemenu: ^0.4.1
  provider: ^5.0.0
  font_awesome_flutter: ^10.4.0
  animations: ^2.0.7
  velocity_x: ^0.4.1
  vxstate: ^2.3.0
  video_player: ^2.6.1
  fl_chart: ^0.62.0
  curved_navigation_bar: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
flutter_native_splash:
  background_image: "assets/images/spla.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/images/auth/
    - assets/images/workout/


  # example:
  fonts:
    - family: Klasik
      fonts:
        - asset: assets/fonts/Klasik Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
